name: Matrix example test

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            id: 111111
          - environment: production
            id: 999999
    steps:
      - name: echo
        run: |
          echo ${{ matrix.environment }}
          echo ${{ matrix.id }}
