name: nx-set-shas test

on:
  workflow_dispatch:
  pull_request:

jobs:
  myjob:
    runs-on: ubuntu-latest
    name: My Job
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v3
        with:
          # The "main" branch of your repository (the base branch which you target with PRs).
          # Common names for this branch include main and master.
          #
          # Default: main
          main-branch-name: "; ls; #"
          # Applies the derived SHAs for base and head as NX_BASE and NX_HEAD environment variables within the current Job.
          #
          # Default: true
          set-environment-variables-for-job: ""
          # By default, if no successful workflow run is found on the main branch to determine the SHA, we will log a warning and use HEAD~1. Enable this option to error and exit instead.
          #
          # Default: false
          error-on-no-successful-workflow: ""
          # The type of event to check for the last successful commit corresponding to that workflow-id, e.g. push, pull-request, release etc.
          #
          # Default: push
          last-successful-event: ""
          # The path where your repository is. This is only required for cases where the repository code is checked out or moved to a specific path.
          #
          # Default: .
          working-directory: ""
          # The ID of the github action workflow to check for successful run or the name of the file name containing the workflow.
          # E.g. 'ci.yml'. If not provided, current workflow id will be used
          #
          workflow-id: ""
      - run: |
          echo "BASE: ${{ steps.setSHAs.outputs.base }}"
          echo "HEAD: ${{ steps.setSHAs.outputs.head }}"
