name: Python application

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./subdir1/subdir2/
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - './subdir1/subdir2/**'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pipenv"

      - name: Install pipenv
        if: steps.changes.outputs.src == 'true'
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        if: steps.changes.outputs.src == 'true'
        run: |
          pipenv install --verbose
          
      - name: Run Python
        if: steps.changes.outputs.src == 'true'
        run: |
          pipenv run python main.py
