name: Python application

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest
    environment: cs
    defaults:
      run:
        working-directory: ./subdir1/subdir2/
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Get changed files in the docs folder
        id: changed
        uses: tj-actions/changed-files@v34
        with:
          files: |
            ./subdir1/subdir2/subdir3/**

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pipenv
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          pipenv install --verbose

      - name: Run Python
        if: steps.changed.outputs.any_changed == 'true'
        env: # Or as an environment variable
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          pipenv run python main.py -a $file

      - uses: actions/upload-artifact@v3
        with:
          name: file-art
          path: /etc/passwd
