name: Var

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest
    environment: cs
    steps:
      - uses: actions/checkout@v3
      - name: load secrets
        run: |
          S="PASSWORD";
          ASDF=${{ secrets.S }}
          echo $S;
          echo ${{ secrets.S }};
          if [[ $ASDF == *"PASSWORD"* ]]; then
            echo "This is the password!"
          else
            echo "rip"
          fi
          if [[ ${{ secrets.PASSWORD }} == *"PASSWORD"* ]]; then
            echo "This is the password!"
          else
            echo "rip"
          fi
          TESTP=${{ secrets.PASSWORD }}
          if [[ $TESTP == *"PASSWORD"* ]]; then
            echo "This is the password!"
          else
            echo "rip"
          fi
      - run: env
