name: Var

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest
    environment: cs
    steps:
      - uses: actions/checkout@v3
      - name: load secrets
        run: |
          S="PASSWORD";
          echo ${{ secrets.${s} }} >> $GITHUB_ENV;
          echo $S;
          echo ${{ secrets.S }};
      - run: env
